/// Flutter icons CustomIcons
/// Copyright (C) 2023 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  CustomIcons
///      fonts:
///       - asset: fonts/CustomIcons.ttf
///
/// 
/// * RPG Awesome, Copyright (c) 2014, Daniela Howe
///         Author:    Daniela Howe & Ivan Montiel
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://nagoshiashumari.github.io/Rpg-Awesome/
///
import 'package:flutter/widgets.dart';

class CustomIcons {
  CustomIcons._();

  static const _kFontFam = 'CustomIcons';
  static const String? _kFontPkg = null;

  static const IconData circleOfCircles = IconData(0xe965, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData corkedTube = IconData(0xe973, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData crossedAxes = IconData(0xe979, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData crossedBones = IconData(0xe97a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData gecko = IconData(0xe9de, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData hornCall = IconData(0xea04, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData hospitalCross = IconData(0xea07, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData knightHelmet = IconData(0xea1a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData largeHammer = IconData(0xea1d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData monsterSkull = IconData(0xea43, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData skull = IconData(0xeaa1, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData targeted = IconData(0xeac5, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData wyvern = IconData(0xeaeb, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
